<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    protected static function boot() {
	    parent::boot(); // TODO: Change the autogenerated stub

	    static::created(function($user){
	    	$user->profile()->create([
	    		'user_id' => $user->id
		    ]);
	    });
    }


	public function profile(){
    	return $this->hasOne(Profile::class);
    }

	public function posts(){
		return $this->hasMany(Post::class)->orderBy('created_at', 'DESC');
	}

	public function comments(){
		return $this->hasMany(Comment::class)->orderBy('created_at', 'DESC');
	}

	public function role(){
		return $this->belongsTo(Role::class);//https://laravel.ru/docs/v5/eloquent-relationships
	}
}
